### ISSUE TITLE
Any chance for a new docker image?

### ISSUE THREAD

**Issue by caruccio** [summerwind/whitebox-controller#5]
Hey @summerwind. Do you plan for a new image on docker hub including PR #3?
I'm trying to avoid to build my own image and sticky with the official one ;)

BTW, this is a really nice project. Thanks.

**Comment by summerwind** [comment]
I just released v0.7.1 and published new container image. Thank you for using!
https://github.com/summerwind/whitebox-controller/releases/tag/v0.7.1
